### PR TITLE
:sparkles: feature to rename/save_as file

### LINKED ISSUE #29: Add a command to rename/save as
Potential commands:

- `:saveas <filename>`
- `:w <filename>`

I think I prefer the second one, as it's what vim implements, and it's also more intuitive.

### PR DESCRIPTION
**Pull request by jim4067**
Fixes #29
 
save_as rename now implemented from the save function

### CODE REVIEW

**Review by brouberol — APPROVED** [review]
Perfect! Thank you! Before merging, would you mind crossing the item off the list in the readme? Thanks!

**Comment by jim4067** [comment]
Done 👍🏾 
So you talked about also updating the help messages with the changes but I could not access it after typing `help`

Also, That white status bar at the bottom, It does not reflect the changes made after renaming the file. How can I fix this?

**Comment by brouberol** [comment]
Hi! I think you could solve both of these questions will the following diff (with some automatic `rustfmt` included)

```diff
λ bo g(jims-dev) g diff

src/editor.rs
───────────────────┐
293: impl Editor { │
───────────────────┘
         }

         if self.document.save(new_name).is_ok() {
-            if new_name.is_empty(){
+            if new_name.is_empty() {
                 self.display_message("File saved successfully".to_string());
             } else {
-            self.display_message(format!("{} successfully renamed as {}", self.document.filename, new_name));
+                self.display_message(format!(
+                    "{} successfully renamed as {}",
+                    self.document.filename, new_name
+                ));
+                self.document.filename = String::from(new_name);
             }
             self.unsaved_edits = 0;
             self.last_saved_hash = self.document.hashed();

───────────────────┐
952: impl Editor { │
───────────────────┘
                             open <filename> => open a file\r\n  \
                             q               => quit bo\r\n  \
                             stats           => toggle line/word stats\r\n  \
-                            w               => save\r\n  \
+                            w [filename]    => save\r\n  \
                             wq              => save and quit\r\n\n\
                         Insert commands\r\n  \
                             Esc => go back to normal mode";
```

**Comment by jim4067** [comment]
Done 👍🏾 

How do I access the help screen?

**Comment by brouberol** [comment]
`:help` will do the trick

**Comment by brouberol** [comment]
Thank you!

**Pull request merged**
